var report_data = [
  
    {
      'DOCNO': '1000',
      'PROJECTCODE': '101',
      'PROJECTNAME': 'Project name ',
      'STARTDATE': '2022-03-30T18:30:00.000Z',
      'ENDDATE': '2022-05-07T18:30:00.000Z',
      'CUSTOMERNAME': 'OCIUZ',
      'ADDRESS': '          ADDRESS 102',
      'CONTRACTVALUE': '2000',
      'PLOTNO': '101',
      'ASSIGNED USERS': 'test,',
      'TYPE': 'Watermeter Replacement'
    },
    {
      'DOCNO': '1001',
      'PROJECTCODE': 'Water meter-0100',
      'PROJECTNAME': 'Water meter-01',
      'STARTDATE': '2021-12-31T18:30:00.000Z',
      'ENDDATE': '2022-12-30T18:30:00.000Z',
      'CUSTOMERNAME': 'ADDC',
      'ADDRESS': '  Abu Dhabi',
      'CONTRACTVALUE': '100000',
      'PLOTNO': '3338',
      'ASSIGNED USERS': 'greeshma,Anand,pmanager,qsurveyor,User,Viewer,',
      'TYPE': 'Watermeter Replacement'
    },
    {
      'DOCNO': '1002',
      'PROJECTCODE': 'Pipeline-01',
      'PROJECTNAME': 'Pipeline-01',
      'STARTDATE': '2021-12-31T18:30:00.000Z',
      'ENDDATE': '2023-12-30T18:30:00.000Z',
      'CUSTOMERNAME': 'ADDC',
      'ADDRESS': ' Abu Dhabi',
      'CONTRACTVALUE': '100000',
      'PLOTNO': '3338',
      'ASSIGNED USERS': 'Anand,pmanager,qsurveyor,User,Viewer,',
      'TYPE': 'Pipeline and Others'
    },
    {
      'DOCNO': '1003',
      'PROJECTCODE': 'Pipeline-04',
      'PROJECTNAME': 'Pipeline-02',
      'STARTDATE': '2020-12-31T18:30:00.000Z',
      'ENDDATE': '2021-12-30T18:30:00.000Z',
      'CUSTOMERNAME': 'ADDC',
      'ADDRESS': '  Abu Dhabi',
      'CONTRACTVALUE': '50000',
      'PLOTNO': '3338',
      'ASSIGNED USERS': 'Anand,Viewer,',
      'TYPE': 'Pipeline and Others'
    },
    {
      'DOCNO': '1004',
      'PROJECTCODE': '102',
      'PROJECTNAME': 'PROJECT TEST',
      'STARTDATE': '2022-04-06T18:30:00.000Z',
      'ENDDATE': '2022-04-30T18:30:00.000Z',
      'CUSTOMERNAME': 'OCIUZ',
      'ADDRESS': 'TEST ',
      'CONTRACTVALUE': '200',
      'PLOTNO': '102',
      'ASSIGNED USERS': 'test,',
      'TYPE': 'Watermeter Replacement'
    },
    {
      'DOCNO': '1005',
      'PROJECTCODE': 'test',
      'PROJECTNAME': 'watermeter test ',
      'STARTDATE': '2022-04-07T18:30:00.000Z',
      'ENDDATE': '2022-05-07T18:30:00.000Z',
      'CUSTOMERNAME': 'OCIUZ',
      'ADDRESS': '  ADDRESS ',
      'CONTRACTVALUE': '20000',
      'PLOTNO': '101',
      'ASSIGNED USERS': 'Anand,',
      'TYPE': 'Watermeter Replacement'
    },
    {
      'DOCNO': '1006',
      'PROJECTCODE': '102',
      'PROJECTNAME': 'WATERMETER OCIUZ',
      'STARTDATE': '2022-04-08T18:30:00.000Z',
      'ENDDATE': '2022-04-23T18:30:00.000Z',
      'CUSTOMERNAME': 'OCIUZ',
      'ADDRESS': '      101',
      'CONTRACTVALUE': '2000',
      'PLOTNO': '101',
      'ASSIGNED USERS': 'test,wassim,Anand,pmanager,qsurveyor,User,Viewer,',
      'TYPE': 'Watermeter Replacement'
    },
    {
      'DOCNO': '1007',
      'PROJECTCODE': '102',
      'PROJECTNAME': 'pipeline test',
      'STARTDATE': '2022-12-08T18:30:00.000Z',
      'ENDDATE': '2022-04-08T18:30:00.000Z',
      'CUSTOMERNAME': 'ociuz',
      'ADDRESS': 'test ',
      'CONTRACTVALUE': '300000',
      'PLOTNO': '101',
      'ASSIGNED USERS': 'test,',
      'TYPE': 'Pipeline and Others'
    },
    {
      'DOCNO': '1008',
      'PROJECTCODE': '101',
      'PROJECTNAME': 'watermeter test1',
      'STARTDATE': '2022-04-10T18:30:00.000Z',
      'ENDDATE': '2022-05-07T18:30:00.000Z',
      'CUSTOMERNAME': 'ociuz',
      'ADDRESS': '     ammathil house varavoor  ',
      'CONTRACTVALUE': '200000',
      'PLOTNO': '101',
      'ASSIGNED USERS': 'test,',
      'TYPE': 'Watermeter Replacement'
    },
  
];
var header = [
  {
    'title': 'DOCNO',
    'field': 'DOCNO',
    'type': 'text',
    'textAlign': 'right',
    'width': 0.0,
  },
  {
    'title': 'PROJECTCODE',
    'field': 'PROJECTCODE',
    'type': 'select',
    'textAlign': 'left',
    'width': 200.0,
    'data': [100, 101, 102]
  },
  {
    'title': 'PROJECTNAME',
    'field': 'PROJECTNAME',
    'type': 'text',
    'textAlign': 'left',
    'width': 200.0,
  },
  {
    'title': 'STARTDATE',
    'field': 'STARTDATE',
    'type': 'date',
    'textAlign': 'left',
    'width': 200.0,
  },
  {
    'title': 'ENDDATE',
    'field': 'ENDDATE',
    'type': 'date',
    'textAlign': 'left',
    'width': 200.0,
  },
  {
    'title': 'CUSTOMERNAME',
    'field': 'CUSTOMERNAME',
    'type': 'text',
    'textAlign': 'left',
    'width': 200.0,
  },
  {
    'title': 'ADDRESS',
    'field': 'ADDRESS',
    'type': 'text',
    'textAlign': 'left',
    'width': 200.0,
  },
  {
    'title': 'CONTRACTVALUE',
    'field': 'CONTRACTVALUE',
    'type': 'text',
    'textAlign': 'right',
    'width': 200.0,
  },
  {
    'title': 'PLOTNO',
    'field': 'PLOTNO',
    'type': 'text',
    'textAlign': 'right',
    'width': 200.0,
  },
  {
    'title': 'ASSIGNED USERS',
    'field': 'ASSIGNED USERS',
    'type': 'text',
    'textAlign': 'left',
    'width': 200.0,
  },
  {
    'title': 'TYPE',
    'field': 'TYPE',
    'type': 'button',
    'textAlign': 'left',
    'width': 300.0,
    'data': [
      {
        'type': 'text_button',
        'color': 'red',
        'action': '',
        'content': 'Delete',
      },
      {
        'type': 'text_button',
        'color': 'green',
        'action': '',
        'content': 'Approve',
      },
      {
        'type': 'icon_button',
        'color': 'blue',
        'action': '',
        'content': 'icon_save',
      },
    ],
  },
];
